modules:
  - name: application
paths:
  # react library
  'react': 'react/react-with-addons'
  'react_ujs': 'react_ujs'
  'react-router': 'react-router/dist/react-router'
  'react-bootstrap': 'react-bootstrap/react-bootstrap'
  'react-rater': 'react-rater/react-rater'
  'flux': 'flux/dist/Flux'
  # event emitter
  'event-emitter2': 'eventemitter2/lib/eventemitter2'
  # require director to handle routing on client-side
  'director': 'director/build/director'
  # REST wrapper
  'superagent': 'superagent/superagent'
  # require jquery library
  'jquery': 'jquery'
  'jquery_ujs': 'jquery_ujs'
  # require lodash
  'lodash': 'lodash/dist/lodash'
  # bootstrap library
  'bootstrap': 'bootstrap-sprockets'
  # require es6-promise
  'es6-promise': 'es6-promise/promise'
  # require event emitter 2
  'eventemitter2': 'eventemitter2/lib/eventemitter2'
  # require alertify
  'alertify': 'alertify/alertify'
  # File API
  'FileAPI': 'FileAPI/dist/FileAPI'
shim:
  'react-with-addons':
    exports: 'React'
  'react-router': ['react']
  'react-bootstrap': ['react']
  'jquery_ujs': ['jquery']
  'lodash':
    exports: '_'
  'director':
    exports: 'Router'
  'bootstrap': ['jquery']
